version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip unzip
      - npm install -g serverless
  build:
    commands:
      - serverless --version
      - cd sample-app
      - mkdir deploy-artifacts
      - serverless package --stage $stage --region $region --package deploy-artifacts
      - cd deploy-artifacts && cp ../../deployspec.yml . && cp ../serverless.yml .
      - aws apigateway get-rest-apis

artifacts:
  files:
    - deploy-artifacts/*
  discard-paths: yes
  base-directory: sample-app