version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless
  build:
    commands:
      - serverless --version
      - cd sample-app
      - mkdir deploy-artifacts
      - serverless package --package deploy-artifacts

artifacts:
  files:
    - deploy-artifacts/*
  discard-paths: yes
  base-directory: sample-app