version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless
  build:
    commands:
      - serverless --version
      - cd sample-app
      - mkdir deploy-artifacts
      - serverless package --package deploy-artifacts
      - cd deploy-artifacts && zip -r ../deploy-artifacts.zip ./*

artifacts:
  files:
    - deploy-artifacts.zip
  discard-paths: yes
  base-directory: sample-app