AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create a health check for an api gateway endpoint

Parameters:
  APIEndpoint:
    Type: String
    Description: Endpoint to health check
  ResourcePath:
    Type: String
    Description: Health check uri

Resources:

  myHealthCheck:
    Type: "AWS::Route53::HealthCheck"
    Properties:
      HealthCheckConfig:
        FullyQualifiedDomainName: !Ref APIEndpoint
        ResourcePath: !Ref ResourcePath
        Type: HTTPS